test.db1:
  jdbcUrl: "jdbc:h2:mem:dbtest;DB_CLOSE_ON_EXIT=FALSE"
  driverClassName: "org.h2.Driver"
  username: "sa"
  password: ""

spring.freemarker:
  template-loader-path: "classpath:/templates"
  cache: false
  charset: UTF-8
  check-template-location: true
  content-type: text/html
  expose-request-attributes: false
  expose-session-attributes: false
  request-context-attribute: request
  suffix: .ftl